services:
  # 1. The Python Backend API
  - type: web
    name: velocity-api
    runtime: docker
    region: oregon 
    plan: free 
    rootDir: velocity-backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: velocity-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  # 2. The PostGIS Database
  - name: velocity-db
    databaseName: velocity_db
    user: velocity_user
    plan: free
    region: oregon
    postgresMajorVersion: 14
    ipAllowList: [] # Allow all for now, restrict later
