version: '3.8'

services:
  db:
    image: kartoza/postgis:14-3.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=password123
      - POSTGRES_DBNAME=velocity_db
    ports:
      - "5433:5432" # Mapping to 5433 as per our troubleshooting
    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Use internal docker dns name 'db' and internal port 5432
      - DATABASE_URL=postgresql+asyncpg://postgres:password123@db:5432/velocity_db
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
